### ISSUE TITLE
Elements flashing on page load

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [zuramai/mazer#10]
Sometimes, around 20% of the time, when a page is loaded, some elements flash with incorrect color for a short period of time. It looks very disorienting.
![image](https://user-images.githubusercontent.com/928550/110037191-5a381000-7d3e-11eb-9658-69bbb79dbb56.png)

**Comment by zuramai** [comment]
May I know what version of Firefox is it?

**Comment by ZimM-LostPolygon** [comment]
Latest Firefox 86.0, Windows 10 20H2 x64.

**Comment by zuramai** [comment]
Can you make a pull request for this issue?

**Comment by ZimM-LostPolygon** [comment]
Pull request? But I haven't made a fix.

**Comment by zuramai** [comment]
Yeah, I mean fix this issue and make a PR. Because I never face this issue in Firefox nor Google Chrome :)
