### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by walawe** [zuramai/mazer#100]
Any plan to incorporate form validation framework into this great template?

**Comment by zuramai** [comment]
Hi @walawe, do you have any recommendation on what form validation framework would it be?

**Comment by walawe** [comment]
jQuery Validation seems to be popular - https://jqueryvalidation.org
Another one could be Parsley - https://parsleyjs.org

I'm happy to contribute once we agree on which framework this template should adopt.

**Comment by walawe** [comment]
validator.js looks good, however it only covers string validations. other things need to be considered:
- integrating validation logic into form fields (e.g. specifying validation logic as attributes)
- ability to write custom validation function (e.g. file upload field, checksum validation, etc)

**Comment by zuramai** [comment]
I guess we'll make two. We'll make the jQuery and the non-jQuery one.
If you are going to make a pull request, it will be appreciated if you make the implementation under "Form Validation" page under the "Forms" menu.

**Comment by walawe** [comment]
@zuramai  #102 is ready for your review.
