### ISSUE TITLE
Add image to horizontal dropdown

### ISSUE THREAD

**Issue by Haeyzed** [zuramai/mazer#105]
Add image to horizontal layout at the nav bar dropdown section. It will be large image type.

**Comment by bagussatoto** [comment]
# @Haeyzed 

## in what line?
## what part folder?

**Comment by zuramai** [comment]
Could you be more specific about the issue?

**Comment by zuramai** [comment]
This issue is closed due to inactivity.

**Comment by Haeyzed** [comment]
![Screenshot from 2022-07-27 19-07-11](https://user-images.githubusercontent.com/59699632/181346938-c49ae7e5-43ac-4c7a-83be-8470bb99f9eb.png)

**Comment by Haeyzed** [comment]
hi Pls update
