### ISSUE TITLE
Datatable with export excel

### ISSUE THREAD

**Issue by habibulilalbaab** [zuramai/mazer#11]
Hi, i try to implement datatable with export excel. i follow this https://datatables.net/extensions/buttons/examples/initialisation/export.html

but i have problem like this:
![image](https://user-images.githubusercontent.com/28334523/118234355-6b7b6680-b4bd-11eb-8692-89f74b862823.png)
can you give me trick to enable export data ?

**Comment by zuramai** [comment]
Remove this default DataTable and change it to another Datatable plugin:
```html
// Remove this
<script src="assets/vendors/simple-datatables/simple-datatables.js"></script>
<script>
    // Simple Datatable
    let table1 = document.querySelector('#table1');
    let dataTable = new simpleDatatables.DataTable(table1);
</script>
```

**Comment by habibulilalbaab** [comment]
its working now. thanks

**Comment by habibulilalbaab** [comment]
its working now. thanks
