### ISSUE TITLE
Registration slider onboarding screen

### ISSUE THREAD

**Issue by Haeyzed** [zuramai/mazer#110]
Create a registration onboarding screen where by you fill form which include
Name, Email, DOB, Adress
and click on next buton to show the remaining form input like
School, Blood Group e.t.c

**Comment by bagussatoto** [comment]
@zuramai

**Comment by Haeyzed** [comment]
Hi do you get my content

**Comment by zuramai** [comment]
Hi @Haeyzed, do you mean Form Wizard?

**Comment by Haeyzed** [comment]
yes, correct and include date picker and date range picker

**Comment by Haeyzed** [comment]
@zuramai

**Comment by Haeyzed** [comment]
ok, thanks.

**Comment by Haeyzed** [comment]
hi
