### ISSUE TITLE
Dockerizing Mazer

### ISSUE THREAD

**Issue by DanielAzulayy** [zuramai/mazer#111]
Hello,
Is it possible to dockerize mazer?

* Figured it out, never mind: (I can do a PR if you would like to dockerize it)

FROM node:16 AS frontend

WORKDIR /frontend
COPY package*.json /frontend
RUN npm install

COPY . /frontend
RUN npm run dev

FROM nginx:latest
COPY --from=frontend /frontend/dist /usr/share/nginx/html

**Comment by DanielAzulayy** [comment]
Hello, 
Is it possible to dockerize mazer?

**Comment by zuramai** [comment]
Hi, I think it would be great if you make a pull request to add the dockerfile :smiley:

**Comment by DanielAzulayy** [comment]
Done :)

**Comment by bagussatoto** [comment]
Done

**Comment by alexgiano** [comment]
Sending build context to Docker daemon  95.51MB
Step 1/8 : FROM node:16 AS frontend
16: Pulling from library/node
311da6c465ea: Pull complete 
7e9bf114588c: Pull complete 
ffd9397e94b7: Pull complete 
513d77925604: Pull complete 
ae3b95bbaa61: Pull complete 
0e421f66aff4: Pull complete 
ca266fd61921: Pull complete 
ee7d78be1eb9: Pull complete 
Digest: sha256:f77a1aef2da8d83e45ec990f45df50f1a286c5fe8bbfb8c6e4246c6389705c0b
Status: Downloaded newer image for node:16
 ---> 1ddc7e4055fd
Step 2/8 : WORKDIR /frontend
 ---> Running in 02d14576ace5
Removing intermediate container 02d14576ace5
 ---> 49ed92f09d4f
Step 3/8 : COPY package*.json /frontend/
 ---> bf3e637275b4
Step 4/8 : RUN npm install
 ---> Running in aa2b7aaad188
npm notice 
npm notice New major version of npm available! 8.19.4 -> 10.5.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.0>
npm notice Run `npm install -g npm@10.5.0` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: mazer@2.3.0
npm ERR! Found: vite@5.0.2
npm ERR! node_modules/vite
npm ERR!   dev vite@"5.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.0.0 || ^4.0.0" from vite-plugin-static-copy@0.13.1
npm ERR! node_modules/vite-plugin-static-copy
npm ERR!   dev vite-plugin-static-copy@"^0.13.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-03-11T18_53_34_534Z-debug-0.log
The command '/bin/sh -c npm install' returned a non-zero code: 1
