### ISSUE TITLE
Fix flickering dark mode

### ISSUE THREAD

**Issue by EvannG1** [zuramai/mazer#118]
Is it possible to use only the dark version?
Or to reverse the default theme (dark instead of light) to avoid the little flash at the beginning of the page loading?

**Comment by fairuzmn** [comment]
> Is it possible to use only the dark version? Or to reverse the default theme (dark instead of light) to avoid the little flash at the beginning of the page loading?

You can add this script after `<body>` tag to prevent that issue

```javascript
const appBody = document.body;
if (localStorage.getItem('theme') == 'theme-dark') {
     appBody.classList.add("theme-dark");
} else {
     appBody.classList.add("theme-light");
};
```

**Comment by fzn0x** [comment]
I think this is need to be fixed. I will added the `type: bug` label

**Comment by seyko1974** [comment]
The script above works for me.

For the inital flashing of the button you can use this script:
`<script>
    // fix the flashing of the button
    const toggler = document.getElementById('toggle-dark');
    if (localStorage.getItem('theme') == 'theme-dark')
        toggler.checked = true;
    else
        toggler.checked = false;
</script>
`

**Comment by seyko1974** [comment]
The script above works for me.

For the initial flashing of the button you can use this script:
```javascript
// fix the flashing of the button
const toggler = document.getElementById('toggle-dark');
if (localStorage.getItem('theme') == 'theme-dark')
    toggler.checked = true;
else
    toggler.checked = false;
```

**Comment by fzn0x** [comment]
> The script above works for me.
> 
> For the initial flashing of the button you can use this script:
> 
> ```js
> // fix the flashing of the button
> const toggler = document.getElementById('toggle-dark');
> if (localStorage.getItem('theme') == 'theme-dark')
>     toggler.checked = true;
> else
>     toggler.checked = false;
> ```

It is just make a button is `checked` by checking the `theme-dark` existence in localStorage.

**Comment by fzn0x** [comment]
> The script above works for me.
> 
> For the initial flashing of the button you can use this script:
> 
> ```js
> // fix the flashing of the button
> const toggler = document.getElementById('toggle-dark');
> if (localStorage.getItem('theme') == 'theme-dark')
>     toggler.checked = true;
> else
>     toggler.checked = false;
> ```

It is just make a button is `checked` by checking the `theme-dark` existence in localStorage.

It is should keep the default check.
