### ISSUE TITLE
Sidebar behavior in Vertical Navbar Layout

### ISSUE THREAD

**Issue by seyko1974** [zuramai/mazer#122]
After hiding and showing the sidebar with the burger-button in the Vertical Navbar Layout, the overlay keeps visible. After pressing the overlay with the mousebutton, it disappears, but the sidebar also disappears.

Is is possible to disable the overlay by default and keep the sidebar visible instead (just toggle the sidebar)?

**Comment by rahulaarora** [comment]
@seyko1974 , @fzn0x I can work on this, can you assign this to me?

**Comment by hs05june** [comment]
Please assign this to me.

**Comment by fzn0x** [comment]
> Please assign this to me.

Sure, PR welcome

**Comment by pranjal6314** [comment]
Kindly assign me this task.

**Comment by fzn0x** [comment]
> Kindly assign me this task.

This task is taken by @hs05june

**Comment by seyko1974** [comment]
This is still an issue

**Comment by seyko1974** [comment]
This is still an issue. Maybe someone else can fix this.

**Comment by AZ-Zaini** [comment]
I hope someone fixes this problem

**Comment by fzn0x** [comment]
I'm not really a big fan of text reproduction, can someone show me the visual on how is it affected?

**Comment by fzn0x** [comment]
This is not something like #118 we can reproduce easily

**Comment by seyko1974** [comment]
![Mazer_Issue_122](https://user-images.githubusercontent.com/32483938/200250738-6032d8fe-6aed-44b0-a381-313a8d577b84.gif)

I would expect that the overlay disappears and the sidebar stays open.
