### ISSUE TITLE
Footer is not fixed at the end of the page.

### ISSUE THREAD

**Issue by RogerGoyer** [zuramai/mazer#155]
Footer is not fixed at the bottom of the page. If the page has little content, the footer starts to climb on the page.

**Comment by rajnish254** [comment]
hey @RogerGoyer , Can you assign it to me. i will like to work on it.

**Comment by fzn0x** [comment]
> hey @RogerGoyer , Can you assign it to me. i will like to work on it.

Since it's `hacktoberfest` labeled issue, I would like everyone to take this, who's the faster he will get the hacktoberfest acception :)

**Comment by baharsah** [comment]
@RogerGoyer can you provide some screenshot about this issue?

**Comment by RogerGoyer** [comment]
![Captura de tela em 2022-10-14 16-11-44](https://user-images.githubusercontent.com/75486827/195923592-4900a06e-a5e1-48a1-a487-834e0cdb374f.png)

The footer is written "Turismo Niterói Dev. It Cast". Instead of being located fixed at the bottom of the page, it stayed at the top of the page
