### ISSUE TITLE
Datable default order

### ISSUE THREAD

**Issue by SrPeterr** [zuramai/mazer#161]
Hi!
For some reason by default the ID is order, I want to order it by another column
I did try with 
```
$(document).ready(function () {
    $('#example').DataTable({
        order: [[6, 'desc']],
    });
});
```
But nothing happens... just this error:
`DataTables warning: table id=table1 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3`

![image](https://user-images.githubusercontent.com/21348463/195697454-3449174e-375b-4db0-9b2b-a2ea998182eb.png)

**Comment by zuramai** [comment]
Make sure your table id is `example`. Or you can change in file `dist/assets/js/pages/datatables.js` in this line

**Comment by SrPeterr** [comment]
> Make sure your table id is `example`. Or you can change in file `dist/assets/js/pages/datatables.js` in this line
> 
> ```js
> let jquery_datatable = $("#table1").DataTable() // change here
> ```

That was it, thanks 😀
