### ISSUE TITLE
Horizontal Layout navbar icons are too down, out of line with text

### ISSUE THREAD

**Issue by rizkytegar** [zuramai/mazer#163]
I use Horizontal Layout, but I think the icon is less attractive because it doesn't align with the text.

Then I moved the <i> tag (bootstrap icon) into the <span> tag

Default mazer

```html
<li class="menu-item ">
    <a href="index.html" class='menu-link'>
        <i class="bi bi-grid-fill"></i><span>Dashboard</span>
    </a>
</li>
```

my code

```html
<li class="menu-item ">
    <a href="index.html" class='menu-link'>
        <span><i class="bi bi-grid-fill"></i> Dashboard</span>
    </a>
</li>
```

### Desktop

left is my code, right is mazer

![L ayout Horizontal - Mazer Admin Dashboard (1)](https://user-images.githubusercontent.com/55475891/195791776-93410abc-6fa7-477f-9eb1-cf04d7b42cab.png)

### Mobile

![Layout Horizontal - Mazer Admin Dashboard](https://user-images.githubusercontent.com/55475891/195792447-809f73d3-d6c8-4ff1-bcb7-1e45198a9b4d.png)

any references or suggestions to align the icon with the text ? . I don't really understand about the front end

**Comment by rizkytegar** [comment]
is there any other idea, to add different color in active menu on horizontal Layout ?

**Comment by rizkytegar** [comment]
![Layout Horizontal - Mazer Admin Dashboard](https://user-images.githubusercontent.com/55475891/195965730-3ff2c454-0b49-457f-884c-fa87ff20ca5d.png)

it's not working

```
<li class="menu-item active">
  <a href="index.html" class="menu-link">
    <span><i class="bi bi-grid-fill"></i> Dashboard</span>
  </a>
</li>
```

**Comment by rizkytegar** [comment]
How about like this?

```html
 <li class="menu-item">
    <a href="/" class='menu-link'>
        <i class="bi bi-grid-fill minus"></i><span>Dashboard</span>
    </a>
</li>
<style>
    .minus{
        margin-top:-11px
    }
</style>
```

it is quite accurate, including in the mobile version

![Layout Horizontal - Mazer Admin Dashboard (1)](https://user-images.githubusercontent.com/55475891/195967457-06f26239-999d-4f63-9336-4a81b34ebea3.png)

**Comment by zuramai** [comment]
Can you make a pull request out of it? Thank you
