### ISSUE TITLE
Template in angularjs

### ISSUE THREAD

**Issue by alebupal** [zuramai/mazer#170]
Hello, has anyone used the template in with angularjs?

I am importing the js from the template like this so that the elements are loaded before the js:
`import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit{
  title = 'test-app';

  ngOnInit() {
    this.loadScript('../assets/js/bootstrap.js');
    this.loadScript('../assets/js/app.js');
  }

  public loadScript(url: string) {
    const body = <HTMLDivElement> document.body;
    const script = document.createElement('script');
    script.innerHTML = '';
    script.src = url;
    script.async = false;
    script.defer = true;
    body.appendChild(script);
  }
}`

I can switch from light to dark theme correctly but when I reload the website it doesn't load the previously chosen theme.

Has anyone had a similar problem?

Thank you very much for the template, it's great!

**Comment by fzn0x** [comment]
You need to use `localStorage` to save your choosed theme, JavaScript does not save variables on refresh and that is working as intended.
