### ISSUE TITLE
[Suggest] Pin Navbar

### ISSUE THREAD

**Issue by Am1nCmd** [zuramai/mazer#179]
First of all, I want to say "Terima kasih sudah membuat project ini, dashboardnya keren sekali."

Secondly, I suggest making a pinned/sticky navbar on top, so that when we scroll down the navbar is still visible, easy to click without scrolling up again :D 

Finally, I hope you can make it haha, and may You always be healthy.

**Comment by zuramai** [comment]
Implemented in v2.0.3
https://github.com/zuramai/mazer/releases/tag/v2.0.3
