### ISSUE TITLE
Bug footer is back

### ISSUE THREAD

**Issue by AZ-Zaini** [zuramai/mazer#182]
in version 2.0.3 the footer bug is back, the footer doesn't stay at the bottom

![Screenshot 2022-12-05 at 06 38 15](https://user-images.githubusercontent.com/44011696/205519810-d93c5356-89f5-4625-96a0-a72a5ba00efc.png)

**Comment by yrehan32** [comment]
is there a solution for this bug?

**Comment by gvnnunes** [comment]
I solved this by removing `display: block!important` from `.`

**Comment by gvnnunes** [comment]
I solved this by removing `display: block!important;` at `.layout-navbar` and changing from `display: unset;` to `display: contents;` at `.navbar-fixed>header`

![image](https://user-images.githubusercontent.com/64788898/207999217-014813a3-859a-4e23-a4d5-5ba52a107d29.png)
![image](https://user-images.githubusercontent.com/64788898/207999560-8929373f-9390-4dbe-a675-0946df405cf8.png)

I don't know if this is the best solution for this problem, but in my case it worked.

**Comment by zuramai** [comment]
This problem is appear to be the effect of #179 solution (making the navbar sticky).
To make it sticky, we should not have the navbar as a flex item, so I was changing it to `display: block` and apparently it bring this issue back.
