### ISSUE TITLE
make package available on npmjs.com

### ISSUE THREAD

**Issue by c33s** [zuramai/mazer#183]
it would be awesome to be able to install this nice theme via npm (then it could be easily integrated in for example symfony projects which are using yarn/npm for js package management). 

i searche on https://www.npmjs.com/search?q=mazer%20bootstrap but found nothing.

**Comment by fzn0x** [comment]
This repository is just a collection of pre-built nunjucks files, we can't publish something like that to npm.

This is just a template, not a library or framework.

**Comment by c33s** [comment]
in my experience it makes perfectly sense to have themes like this as package on npmjs. if you use sass and yarn in your project to integrate bootstrap it comes handy to also have the themes as a npm dependency. this is the only way you can easily version manage them.

- https://www.npmjs.com/package/bootswatch
- https://www.npmjs.com/search?q=bootstrap%20theme
- https://symfony.com/doc/current/frontend/encore/bootstrap.html

just my thoughts

**Comment by fzn0x** [comment]
If in that case that could work

**Comment by zuramai** [comment]
The example you provided (bootswatch) is only provide you sass files that consist of set of variables that will override the default bootstrap's theme.

We will consider this to be implemented in the future. Thanks!

**Comment by zuramai** [comment]
Update: Symfony version is implemented, check this out: https://github.com/jvl1v5/symfony-mazer
