### ISSUE TITLE
datatable jquery is not responsive

### ISSUE THREAD

**Issue by ashickur-rahman** [zuramai/mazer#184]
I was trying datatable jquery, I noticed it is not fully responsive. When I check the code, according to datatable [example](https://datatables.net/extensions/responsive/examples/styling/bootstrap5.html) some additional js and css are missing. 

<img width="946" alt="Screenshot 2022-12-19 at 1 07 15 AM" src="https://user-images.githubusercontent.com/43941605/208344373-da2f3757-79eb-484a-bbb6-54ea31314264.png">

**Comment by gvnnunes** [comment]
Are you using a div with `.table-responsive` class before your table attribute ?

I also use these attributes when declaring DataTable to make it 100% responsive.

![image](https://user-images.githubusercontent.com/64788898/208435898-71e7bb48-67cd-4db7-9378-b981fae0319e.png)

**Comment by gvnnunes** [comment]
Are you using a div with `.table-responsive` class before your table attribute ?

I also use these attributes when declaring DataTable to make it 100% responsive.

![image](https://user-images.githubusercontent.com/64788898/208435898-71e7bb48-67cd-4db7-9378-b981fae0319e.png)

**Comment by ashickur-rahman** [comment]
> Are you using a div with `.table-responsive` class before your table attribute ?
> 
> I also use these attributes when declaring DataTable to make it 100% responsive.
> 
> ![image](https://user-images.githubusercontent.com/64788898/208435898-71e7bb48-67cd-4db7-9378-b981fae0319e.png)

I haven’t changed anything, I just open the page, and checked the responsiveness
