### ISSUE TITLE
Notification Badge

### ISSUE THREAD

**Issue by pratamaaudi** [zuramai/mazer#192]
Hello any planning for add support for notification counter badge ?

like this
<img width="57" alt="image" src="https://user-images.githubusercontent.com/20970715/211435930-f36eef70-c55c-41aa-8474-d4b212224335.png">

or with number inside

thanks

**Comment by zuramai** [comment]
It's a nice feature, we really appreciate it if someone can make a pull request for this

**Comment by pratamaaudi** [comment]
> It's a nice feature, we really appreciate it if someone can make a pull request for this 

I already make a PR for this, could you review it ?

**Comment by zuramai** [comment]
Thank you!
