### ISSUE TITLE
Active submenu

### ISSUE THREAD

**Issue by dipras** [zuramai/mazer#198]
![image](https://user-images.githubusercontent.com/51155424/218296687-932ed74f-66fe-4d66-a696-904bc8b3ee1f.png)
Maybe we need active submenu to know which menu we chose? Maybe we can add underline or different color text or something

**Comment by jvl1v5** [comment]
Hi,

what do you mean exactly?

I would say its all there. Screenshot from the demo page.

![grafik](https://user-images.githubusercontent.com/10522892/218300055-9acc6b61-075d-496c-8fec-ccc01e299eab.png)

**Comment by dipras** [comment]
> Hi,
> 
> what do you mean exactly?
> 
> I would say its all there. Screenshot from the demo page.
> 
> ![grafik](https://user-images.githubusercontent.com/10522892/218300055-9acc6b61-075d-496c-8fec-ccc01e299eab.png)

Hmmmm look like i have problem with my browser. My browser does'nt
