### ISSUE TITLE
referenced file not available

### ISSUE THREAD

**Issue by ondiekisteven** [zuramai/mazer#20]
The CSS file 'assets/vendors/fontawesome/all.min.css' references a file which could not be found:
  assets/vendors/webfonts/fa-brands-400.eot

but seems like the folder assets/vendors/webfonts does not exist

is there a fix for this?

**Comment by zuramai** [comment]
does your folder structure match to the corresponding url?

**Comment by DoanhNV** [comment]
Error when i run this command:
**npm install react-mazer-ui --save**

> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-mazer-ui - Not found
> npm ERR! 404
> npm ERR! 404  'react-mazer-ui@latest' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\ngova\AppData\Roaming\npm-cache\_logs\2021-08-06T07_40_52_320Z-debug.log

**Comment by bl0cknumber** [comment]
I would recommend creating a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example), since it's not default bug coming from Mazer, you may need solid example to get help from us. You can ask to reopen anytime or create a new PR with MRE instead.
