### ISSUE TITLE
landing page gak ada ya

### ISSUE THREAD

**Issue by mizzcode** [zuramai/mazer#201]
ini hanya dashboard aja kah?

**Comment by bagussatoto** [comment]
Ga juga
Banyak fitur didalamnya

**Comment by mizzcode** [comment]
Ada tutorial ga sih bang? Buat ngatur template ini. pusing saya

Pada tanggal Min, 12 Mar 2023 13.50, BAGUS BUDI SATOTO <
***@***.***> menulis:

**Comment by bagussatoto** [comment]
@mizzcode belum ada tutorial ini..
Soalnya kita kerjakan bersama sama..
jadi belum sempat bikin dokumentasinya
melalui media
