### ISSUE TITLE
Accordion (active) submenu in sidebar didn't work as well

### ISSUE THREAD

**Issue by alfianchii** [zuramai/mazer#205]
'active' class didn't appears in Components>Accordion.

![image](https://user-images.githubusercontent.com/76430369/227763573-31b0b501-edba-45f0-83ed-2bf7f5437482.png)

**Comment by zuramai** [comment]
Closed as [265ce07](https://github.com/zuramai/mazer/commit/265ce07db434fd9b32448ee178f4c27abe69c0b5)
