### ISSUE TITLE
Margin and padding issues which change suddenly when do dark mode

### ISSUE THREAD

**Issue by alfianchii** [zuramai/mazer#207]
Sometimes I experience weirdness when I'm in dark mode, which the margin/padding changing suddenly (not in accordance with light mode).

For example, in the search input of the datatable:
![image](https://user-images.githubusercontent.com/76430369/227764923-18898c9a-08b2-4cc5-813a-78f156bc0308.png)

When the dark mode clicked, then:
![image](https://user-images.githubusercontent.com/76430369/227764942-16623a78-9245-4dbc-b686-94eb997b3348.png)

In my case:
Light mode is fine.
![image](https://user-images.githubusercontent.com/76430369/227764988-0b3feab6-4f57-4417-bba7-fa7b8bce67fd.png)

But in dark mode, some designs are ruined.
![image](https://user-images.githubusercontent.com/76430369/227765065-360c2405-1a2e-47dd-949b-79416d1daad9.png)

**Comment by zuramai** [comment]
Can you elaborate more on how the fonts could changed on dark mode in the second case?

**Comment by alfianchii** [comment]
In light mode, the font-size was fixed (**px**). But when in dark mode, the font-size becomes **rem**. Anyway, the fonts could change only in mobile view (perhaps because my front-end was config his own CSS).


![image](https://user-images.githubusercontent.com/76430369/228501670-03b16d65-bbae-46ac-b2ba-009a988bb383.png)
![image](https://user-images.githubusercontent.com/76430369/228501758-7143d6d2-d23f-4bab-a52a-be24b294b845.png)


But this problem was solved by my front-end in [our repository](https://github.com/alfianchii/confess/commit/4299cdfddb9a3badbf962c752b178da3e6a14f08) by overriding **rem** with **px** xD.

**Comment by alfianchii** [comment]
In other words, in my case the problem was solved. But still in the most case, like the search input in simple datatable, the margin/padding would change suddenly when do dark mode.

**Comment by alfianchii** [comment]
> In other words, in my case the problem was solved. But still in the most case, like the search input in simple datatable, the margin/padding would change suddenly when do dark mode.

My mistake. The margin/padding bug in simple datatable was solved. I should have checked on [branch vite](https://github.com/zuramai/mazer/commits/vite) not in the production D:
