### ISSUE TITLE
Comment component

### ISSUE THREAD

**Issue by alfianchii** [zuramai/mazer#210]
Can you add a comment component with it? I'm struggling when faced with this—decide their own layouts. Like, the buttons of view, edit, delete or position of the image profile,

![image](https://user-images.githubusercontent.com/76430369/228848514-468bc89b-2ea1-43c7-9c4c-ec12284225a0.png)
![image](https://user-images.githubusercontent.com/76430369/228849109-098cb4e9-2cd4-4907-8bba-f3471ede5f59.png)

**Comment by VaibhavSharma24** [comment]
I would love to add comment component there please assign me this issue

**Comment by alfianchii** [comment]
> I would love to add comment component there please assign me this issue

Please make your own PR, sir. Therefore, I would like to review your PR.

**Comment by SurajPrakash24** [comment]
Can You please assign it to me. I want to work on this feature.

**Comment by alfianchii** [comment]
> Can You please assign it to me. I want to work on this feature.

You can make a PR and my pleasure to review your PR. Thanks.

**Comment by Haribhajank** [comment]
Hey @alfianchii can you explain a little bit more , like exactly what changes you want to see and where .

**Comment by alfianchii** [comment]
> Hey @alfianchii can you explain a little bit more , like exactly what changes you want to see and where .

Just like this @Haribhajank. Can you?

![image](https://github.com/zuramai/mazer/assets/76430369/8707420e-73c8-4e86-a4f9-eb3cd3dedbe7)

**Comment by alfianchii** [comment]
> Hey @alfianchii can you explain a little bit more , like exactly what changes you want to see and where .

Just like this, @Haribhajank.

![image](https://github.com/zuramai/mazer/assets/76430369/da848770-cc4f-43e3-9130-c0b4e31fc1f7)

**Comment by Haribhajank** [comment]
Hey @alfianchii , I have created a comment component , and I am sharing with you some screenshot to suggest any changes if you want .
![Screenshot (158)](https://github.com/zuramai/mazer/assets/106884012/ffa7c8e7-8389-4b36-ac61-6f396661f91f)

**Comment by alfianchii** [comment]
> Hey @alfianchii , I have created a comment component , and I am sharing with you some screenshot to suggest any changes if you want .
> ![Screenshot (158)](https://github.com/zuramai/mazer/assets/106884012/ffa7c8e7-8389-4b36-ac61-6f396661f91f)
> 

Can you make a PR with it?

**Comment by Haribhajank** [comment]
@alfianchii made a PR.

**Comment by alfianchii** [comment]
@Haribhajank TYSM!!
