### ISSUE TITLE
User Agent Stylesheet Overwrite Writen CSS

### ISSUE THREAD

**Issue by fncolon** [zuramai/mazer#22]
User Agent Stylesheet by default overwrite written CSS in any browsers.
I found this bug by research recently in some browser i.e Firefox, Chrome, and Brave after reading this issue #21.

![Capture](https://user-images.githubusercontent.com/50759463/126229921-612f509e-89a0-42f5-bee8-fa220b017643.PNG)
![Capture2](https://user-images.githubusercontent.com/50759463/126229925-dd793402-f736-4377-8ac2-81252ba0ebb4.PNG)
![Capture3](https://user-images.githubusercontent.com/50759463/126229930-8f70bd0f-9b67-49fc-97f9-587c6123db8a.PNG)
![Capture4](https://user-images.githubusercontent.com/50759463/126229934-c0d9b15c-adf0-4d7f-80da-42b441abe685.PNG)

**Comment by zuramai** [comment]
It's caused by the bootstrap update before. Solved by changing the scss variable

**Comment by zuramai** [comment]
possibly closes #10
