### ISSUE TITLE
Select 2

### ISSUE THREAD

**Issue by rizqisamawa** [zuramai/mazer#220]
Apa bisa ditambahkan plugin select 2 dengan bootstrap 5, sekaligus penyesuaian dark modenya juga

Oh ya gw suka banget ama templatenya, thanks

**Comment by zuramai** [comment]
Halo, untuk select bisa menggunakan Choices.js ya

https://zuramai.github.io/mazer/demo/form-element-select.html

**Comment by rizqisamawa** [comment]
ya ga liat detail dilist menu select, makanya saya closed, tq"
