### ISSUE TITLE
How to fix datatables jquery not responsive? 

### ISSUE THREAD

**Issue by WhisperGo** [zuramai/mazer#229]
![image](https://user-images.githubusercontent.com/122973372/233826956-be8f46bb-85d8-4566-b5c3-2a8e3cd0d308.png)

![image](https://user-images.githubusercontent.com/122973372/233826862-eaca1d22-2672-4113-b650-d2844ed69198.png)

I already use div table-responsive before declare datatables, but when i add like 10<th> and i scroll the table to right, the search and pagination button become like that (in picture)? 

Can anyone help me? Sorry for my bad english. Thankyou👌

**Comment by zuramai** [comment]
Yes, the pagination buttons will be centered in the mobile and tablet screen. This is the default style of jQuery Datatables for Bootstrap 5. You can [check more examples for jQuery Datatables](https://datatables.net/examples/styling/bootstrap5.html) for reference.

**Comment by WhisperGo** [comment]
> Yes, the pagination buttons will be centered in the mobile and tablet screen. This is the default style of jQuery Datatables for Bootstrap 5. You can [check more examples for jQuery Datatables](https://datatables.net/examples/styling/bootstrap5.html) for reference.

But, im designing my web for computer. Can the pagination button placed in the right screen?

**Comment by zuramai** [comment]
Yes you can. 
I have made a minimal example for a datatables that place the pagination button on the right of the screen.

Check [table-datatable-jquery.html](https://zuramai.github.io/mazer/demo/table-datatable-jquery.html)

**Comment by WhisperGo** [comment]
> Yes you can. I have made a minimal example for a datatables that place the pagination button on the right of the screen.
> 
> Check [table-datatable-jquery.html](https://zuramai.github.io/mazer/demo/table-datatable-jquery.html) ([4e06a68](https://github.com/zuramai/mazer/commit/4e06a68074447736618c9fdde3863bac1ae1e8c1))


Thank youu
