### ISSUE TITLE
When will be available the horizontal layout ?

### ISSUE THREAD

**Issue by lilouch** [zuramai/mazer#23]
Thank a lot for your good work. Love what you have done so far.

I would like to know if you know when you will release the horizontal layout (https://zuramai.github.io/mazer/demo/layout-horizontal.html) ?

Thank you

**Comment by zuramai** [comment]
Approximatedly August 2021.
Currently I couldn't spare a time to add additional features, but I'm accepting contribution and pull request either.

**Comment by zuramai** [comment]
Added. Check out pull request #25
