### ISSUE TITLE
h1, h2, h3, h4, h5, h6 font color wrong color in light mode, but not in dark mode.

### ISSUE THREAD

**Issue by WhisperGo** [zuramai/mazer#230]
When im using h4 in dark mode the color of the font is white, but when im change to light mode, the color of font is grey. Is it not a mistake? 

My code : 
```
<div class="card-header bg-primary">
          <h4 class="card-title d-flex justify-content-center align-items-center">Horizontal Form with Icons</h4>
</div>
```

Dark Mode : 
![image](https://user-images.githubusercontent.com/122973372/234278279-dfd5b00a-e30f-4fca-91c0-2f8cc0b1c930.png)

Light Mode : 
![image](https://user-images.githubusercontent.com/122973372/234278340-eead3564-b029-4dbc-a356-910df310ed77.png)

**Comment by zuramai** [comment]
By default, the headings element has darker color in light mode. If you want to keep the text to be white, you can add `text-white` class to the element.

Fixed code:

```html
<div class="card-header bg-primary">
     <h4 class="card-title text-white d-flex justify-content-center align-items-center">Horizontal Form with Icons</h4>
</div>
```

**Comment by WhisperGo** [comment]
> By default, the headings element has darker color in light mode. If you want to keep the text to be white, you can add `text-white` class to the element.
> 
> Fixed code:
> 
> ```html
> <div class="card-header bg-primary">
>      <h4 class="card-title text-white d-flex justify-content-center align-items-center">Horizontal Form with Icons</h4>
> </div>
> ```



Thank youuu😁✌️
