### ISSUE TITLE
Sidebar links issue in iOS needing double-tap

### ISSUE THREAD

**Issue by ak-epcc** [zuramai/mazer#239]
When the sidebar is opened in iOS, it needs a double-tap on any link (including the close) before they are followed.

On the first tap, the scrollbars appear on the sidebar but the link isn't followed.

**Comment by jvl1v5** [comment]
Abwesenheitsnotiz:


Vom 22.06.2023  bis einschließlich 11.07.2023  bleibt unser Büro geschlossen. E-Mails werden entsprechend der Dringlichkeit verzögert bearbeitet.


In Notfällen benutzen Sie bitte das telefonische Notfallsystem unter 02206-95100-0.


Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während wir abwesend sind.

Beste Grüße
1 Qubit - J.Suing


-------------------------------------------------------------------------
1 Qubit - J.Suing
Laurentiusstr. 41 - 51789 Lindlar
fon: 02206-95100-0 - fax: 02206-95100-29

Portfolio
STARFACE Telefonanlagen
Software-Entwicklung
Firewall, Security, UTM, VPN
Mailserver / Unified Messaging
CRM / ERP


Partner
STARFACE Advanced Partner
STARFACE Module Creator
Securepoint Professional Partner
Tobit Software Authorized Partner
work4all! Solution Partner
Kerio Partner

Blog, Forum, Module und mehr...
www.1qubit.de
-------------------------------------------------------------------------




  
When the sidebar is opened in iOS, it needs a double-tap on any link (including the close) before they are followed.

On the first tap, the scrollbars appear on the sidebar but the link isn't followed.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/zuramai/mazer/issues/239

**Comment by ak-epcc** [comment]
Commenting to keep open

**Comment by ak-epcc** [comment]
Issue appears to be caused by perfect-scroll but I made multiple changes in my local copy and one fixed it!

When I get chance, will pull fresh and try individual changes to see what is causing the issue.
