### ISSUE TITLE
Choices js max 5 limit

### ISSUE THREAD

**Issue by bhaviljain68** [zuramai/mazer#24]
Hi, I'm using you theme in my project.

The issue I'm having is that when using a choices js component, I'm unable to select more than 5 items.
I checked choices.js file and couldn't find any setting that limits to 5 items... 

How can I configure it to allow more than 5?
Its supposed to be unlimited by default right? 

Also, is it possible to allow items that are not already there in the pre defined list??

Thanks

**Comment by zuramai** [comment]
It should be the issue of Choices.js, not this template instead. Check out Choices.js repository ([https://github.com/Choices-js/](https://github.com/Choices-js))

**Comment by bhaviljain68** [comment]
Hi Zuramai, I did that already.. And then came here... I checked the documentation for choices js and according to that, the property "max_allowed_items" is set to -1 by default, which means unlimited, and even in the choices.js supplied with the theme, I checked the DEFAULT_CONFIG object, the property max_allowed_items is set to -1.

Considering that you chose choices.js for your project, I assumed that you must have had experience with it, hence I asked you.

**Comment by zuramai** [comment]
I think there's no configuration in it. 
Because `max_allowed_items` is how many items you can put in the select, not how many items you can select.

In the mazer example, I can do select more than 5 items. Is this what you referring to?
![image](https://user-images.githubusercontent.com/45036724/127760483-d779ea23-b028-4d30-bdc7-a2b81bb133d0.png)

**Comment by bhaviljain68** [comment]
Hi @zuramai 
Thank you for the response, sry my system was at my workplace during the weekend, hence couldn't reply.

I'm sry I forgot to mention that I was referring to `Multiple Select with Remove Button` component

![Screenshot (143)](https://user-images.githubusercontent.com/40825956/127823927-d8b16642-3e62-4128-913c-52429b44de1d.png)

this is from your demo link :  https://zuramai.github.io/mazer/demo/form-element-select.html

**Comment by zuramai** [comment]
I'm sorry, it was my bad. Now you can edit the `maxItemCount` in `dist/assets/js/pages/form-element-select.js`. 

Check it out the demo link now [https://zuramai.github.io/mazer/demo/form-element-select.html](https://zuramai.github.io/mazer/demo/form-element-select.html)

![image](https://user-images.githubusercontent.com/45036724/127828583-d1a3c248-ac80-40f6-b415-af8b954cb27c.png)

**Comment by bhaviljain68** [comment]
Hey @zuramai ... Thank you for the quick fix... :) 

BTW, any idea on allowing dynamic items by user input? 
I know it's a choices.js thing...
But asking you since you have experience with the library...and in hopes of saving myself some efforts.... 😬😬

**Comment by zuramai** [comment]
Check this out [https://github.com/Choices-js/Choices#setchoiceschoices-value-label-replacechoices](https://github.com/Choices-js/Choices#setchoiceschoices-value-label-replacechoices)

**Comment by bhaviljain68** [comment]
@zuramai ... Thank you, with a bit of JS trickery, this might just work!! 😀😀
