### ISSUE TITLE
how to initialize dropdown menu and notification-dropdown

### ISSUE THREAD

**Issue by ghost** [zuramai/mazer#253]
how to initialize dropdown menu
i ' m using laravel with livewire 3
data-bs-toggle="dropdown"  and notification-dropdown

**Comment by sudeepa88** [comment]
Could you please share the screenshot?

**Comment by alfianchii** [comment]
> how to initialize dropdown menu i ' m using laravel with livewire 3 data-bs-toggle="dropdown" and notification-dropdown

Regarding your issue, you have a problem on Mazer w/ Laravel (Livewire). Therefore, you can create this issue on [Mazer w/ Laravel +  Livewire](https://github.com/zuramai/laravel-mazer). If it pleases you, please readdress this issue. Thanks.

**Comment by mocfaisal** [comment]
> how to initialize dropdown menu i ' m using laravel with livewire 3 data-bs-toggle="dropdown" and notification-dropdown

hey mate i'm using **livewire 3** too on current project
if you build SPA application, and using attribute **wire:navigate** on a link [Livewire 3 Navigate](https://livewire.laravel.com/docs/navigate#basic-usage)

Previously i'm having this issue, fixed when using attribute **data-navigate-track**, but the sidebar got bug like this issue  #257 

My configuration
set javascript file to like this
```blade
<script src="{{ asset('assets/backend') }}/compiled/js/app.js" data-navigate-once></script>
```

Add attribute **data-navigate-once** to load only once
And add the initialize sidebar when navigating to another component / page

```javascript
<script data-navigate-once>
        document.addEventListener('livewire:navigated', () => {
            // NOTE Reinitialize Sidebar
            const sidebar = new window.Sidebar(document.getElementById("sidebar"), {
                recalculateHeight: true
            })
        });
</script>
```
So the dropdown at navbar will be solved
