### ISSUE TITLE
jsdelivr cdn?

### ISSUE THREAD

**Issue by SmileYzn** [zuramai/mazer#256]
First of all, thanks for hard work!

And this n1ce template can be hosted on jsdelivr too?

Thanks 🙏

**Comment by billalxcode** [comment]
[jsdelivr.net](http://jsdelivr.net) has provided a github based cdn service. But this repository does not meet the qualifications.
The qualification is that this repository must have build results files. Like the dist folder or something else, why? because later jsdelivr.net will direct the CDN to the build file.

**Comment by billalxcode** [comment]
An example is as follows

```
http://cdn.jsdelivr.net/gh/user/repo@version/file
```
Example url in this repo
```
http://cdn.jsdelivr.net/gh/zuramai/mazer/src/xxx
```

Websites must load CSS files, but in this repository there are no CSS files unless we have to change the SCSS file to CSS first so that it can be loaded by the web browser. How to build it? This repository already has an application for building assets, namely using Vite.

[Read full docs](https://www.jsdelivr.com/documentation)

**Comment by SmileYzn** [comment]
> [jsdelivr.net](http://jsdelivr.net) has provided a github based cdn service. But this repository does not meet the qualifications. The qualification is that this repository must have build results files. Like the dist folder or something else, why? because later jsdelivr.net will direct the CDN to the build file.

That is why i'm asking for a full package on jsdelivr.net 👍

**Comment by billalxcode** [comment]
Hello, to use Mazer CDN please use the url with the prefix
```
https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist
```

simple example, if you want to load the `app.css` file in `assets/compiled/css/app.css`, then the complete URL is
```
https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/compiled/css/app.css
```

An example of the full code is like this
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - Mazer Admin Dashboard</title>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/scss/themes/dark/app-dark.scss">

    <link rel="shortcut icon" href="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/compiled/svg/favicon.svg" type="image/x-icon">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/compiled/css/app.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/compiled/css/app2.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/compiled/css/iconly.css">
</head>

<body>

    <!-- Start content here -->

    <!-- End content --->

    <script src="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/static/js/initTheme.js"></script>

    <script src="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/static/js/components/dark.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/extensions/perfect-scrollbar/perfect-scrollbar.min.js"></script>

    <script src="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/compiled/js/app.js"></script>
</body>

</html>
```

**Comment by billalxcode** [comment]
> Hello, to use Mazer CDN please use the url with the prefix
> 
> ```
> https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist
> ```
> 
> simple example, if you want to load the `app.css` file in `assets/compiled/css/app.css`, then the complete URL is
> 
> ```
> https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/compiled/css/app.css
> ```
> 
> An example of the full code is like this
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> 
> <head>
>     <meta charset="UTF-8">
>     <meta name="viewport" content="width=device-width, initial-scale=1.0">
>     <title>Dashboard - Mazer Admin Dashboard</title>
> 
> 
>     <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/scss/themes/dark/app-dark.scss">
> 
>     <link rel="shortcut icon" href="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/compiled/svg/favicon.svg" type="image/x-icon">
> 
>     <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/compiled/css/app.css">
>     <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/compiled/css/app2.css">
>     <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/compiled/css/iconly.css">
> </head>
> 
> <body>
> 
>     
> 
>     
> 
>     <script src="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/static/js/initTheme.js"></script>
> 
>     <script src="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/static/js/components/dark.js"></script>
>     <script src="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/extensions/perfect-scrollbar/perfect-scrollbar.min.js"></script>
> 
>     <script src="https://cdn.jsdelivr.net/gh/billalxcode/mazer@dist/dist/assets/compiled/js/app.js"></script>
> </body>
> 
> </html>
> ```

The CDN above is an unofficial CDN. Because the official Mazer does not yet provide a CDN feature.

**Comment by billalxcode** [comment]
Or you can use the demo page as the official CDN from Mazer.

## How to use it?
Here's a simple example of using Mazer CDN

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - Mazer Admin Dashboard</title>

    <link rel="shortcut icon" href="https://cdn.jsdelivr.net/gh/zuramai/mazer@docs/demo/assets/compiled/svg/favicon.svg" type="image/x-icon">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zuramai/mazer@docs/demo/assets/compiled/css/app.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zuramai/mazer@docs/demo/assets/compiled/css/app-dark.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zuramai/mazer@docs/demo/assets/compiled/css/iconly.css">
</head>

<body>
    <script src="https://cdn.jsdelivr.net/gh/zuramai/mazer@docs/demo/assets/static/js/initTheme.js"></script>
    <!-- Start content here -->

    <!-- End content -->
    <script src="https://cdn.jsdelivr.net/gh/zuramai/mazer@docs/demo/assets/static/js/components/dark.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/zuramai/mazer@docs/demo/assets/extensions/perfect-scrollbar/perfect-scrollbar.min.js"></script>

    <script src="https://cdn.jsdelivr.net/gh/zuramai/mazer@docs/demo/assets/compiled/js/app.js"></script>

    <!-- Need: Apexcharts -->
    <script src="https://cdn.jsdelivr.net/gh/zuramai/mazer@docs/demo/assets/extensions/apexcharts/apexcharts.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/zuramai/mazer@docs/demo/assets/static/js/pages/dashboard.js"></script>

</body>

</html>
```

You can use a url with a prefix
```
https://cdn.jsdelivr.net/gh/zuramai/mazer@docs/demo
```

A simple example is like this
```
https://cdn.jsdelivr.net/gh/zuramai/mazer@docs/demo/assets/compiled/css/app.css
```

**Comment by billalxcode** [comment]
Actually, Mazer hasn't released an official CDN yet. It just makes the demo page as a CDN only. contact @zuramai for details

**Comment by SmileYzn** [comment]
Thanks for help 🙏 

But author should really to do a jsdelivr package
