### ISSUE TITLE
The input tag is long beyond the modal.

### ISSUE THREAD

**Issue by EKAPHONG** [zuramai/mazer#268]
The input tag is long beyond the modal.
Screenshort: 
![image](https://i.imgur.com/HY1XwEj.png)

**Comment by billalxcode** [comment]
Hello, after I checked the following page https://zuramai.github.io/mazer/demo/extra-component-sweetalert.html, I didn't find a long input size. Take a look at the following screenshot...

![image](https://github.com/zuramai/mazer/assets/71764176/00854f4b-9c01-43be-9fa0-42ce706bed96)

Please try updating the repository by running ```git pull```

**Comment by hersag** [comment]
@bilal it looks fine in dark mode. try the light mode to see it. 
btw, other alert inputs have the same problem too

**Comment by billalxcode** [comment]
https://github.com/zuramai/mazer/blob/6e181b6c43583be6b3d3eeaee41f3ae1f6f4a2d8/src/assets/static/js/pages/sweetalert2.js#L3

After just checking, it is true that there is a bug in light mode. Please open the file `assets/static/js/pages/sweetalert2.js` there is a cutstom class for input. If you delete customClass input or delete the contents of customClass > input then the bug will disappear. I haven't found another solution yet.

**Comment by billalxcode** [comment]
Another alternative is to change the `width `of the `.form-control` class to initial. An example is like this

```css
.form-control {
   width: 100%;
}
```

then change it to
```css
.form-control {
   width: initial;
}
```
