### ISSUE TITLE
https://registry.npmjs.org/react-mazer-ui - Not found

### ISSUE THREAD

**Issue by DoanhNV** [zuramai/mazer#27]
Error when i run this command:
**npm install react-mazer-ui --save**

> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-mazer-ui - Not found
> npm ERR! 404
> npm ERR! 404 'react-mazer-ui@latest' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.

**Comment by fachryansyah** [comment]
hii 👋 thank you for reminder me to publish into NPMJS
now already published, check this out:
https://www.npmjs.com/package/react-mazer-ui
