### ISSUE TITLE
Enhance: The Buttons in the Header Section Lacks Transition

### ISSUE THREAD

**Issue by DeepRahangdale** [zuramai/mazer#271]
Adding a transition of scale 95/105 on Hovering Over them !!
similar to this site.
https://drive.google.com/file/d/1Gm2KpWL_40dTaTYSwiTKyI3HPI0nPcQw/view?usp=sharing

**Comment by alfianchii** [comment]
Thank you for your feedback on this issue! I appreciate your interest and enthusiasm for this project. However, this issue contains vagueness. Therefore, if you find an issue, you can describe it clearly and in detail. I'm closing this issue now.
