### ISSUE TITLE
Request extra component for flags country

### ISSUE THREAD

**Issue by billalxcode** [zuramai/mazer#273]
I would like to propose adding a extra component for flags country to the Mazer template, this is inspired by one of the bootstrap templates called [tabler](http://tabler.io). Mazer flags have the function of representing countries or languages ​​visually.

**Comment by zuramai** [comment]
What library would it be?

**Comment by billalxcode** [comment]
It is not a library, but an additional component that serves to represent countries or flags visually. This feature was created using scss and svg assets obtained from [here](https://github.com/hampusborgos/country-flags). Don't worry, this SVG asset does not have a license, so it is free to use freely.
