### ISSUE TITLE
Request cookie consent feature

### ISSUE THREAD

**Issue by billalxcode** [zuramai/mazer#276]
Hi, I have a new feature idea for the Mazer app. This feature is the *cookie consent* feature, where when a user opens a page, a modal or component will appear with two options. The first option is to Reject Cookies, and the second is to Accept Cookies.

This is useful for developers who want to utilize cookies. The following is an example of a component design that I will make, maybe this design will change if this design is not relevant to Mazer's design.

![Image](https://freefrontend.com/assets/img/bootstrap-cookie-consent/bootstrap-4-dark-allow-cookie-consent-card.png)

**Comment by zuramai** [comment]
I think we can make it with Mazer (Bootstrap) modal
