### ISSUE TITLE
How to disable dark mode when user first time go to my web?

### ISSUE THREAD

**Issue by WhisperGo** [zuramai/mazer#277]
So, when i try open my web in incognito mode, my login page become dark mode, and i want to change the default theme become light mode? Is that possible?

Dark mode : 
![image](https://github.com/zuramai/mazer/assets/122973372/8ff6be97-01e3-4768-b456-70d79d711075)

Light Mode :
![image](https://github.com/zuramai/mazer/assets/122973372/c10d9c25-db08-478c-b928-b6b6a5791cb2)

**Comment by alfianchii** [comment]
Was your mode dark before you entered the login page?

**Comment by WhisperGo** [comment]
> Was your mode dark before you entered the login page?

Yes, its true. And if you go in mazer demo web, when you first time go to there, the dark mode is toggled on by default.

Can you help me with this problem?

**Comment by alfianchii** [comment]
On first load, by default, Mazer's mode is light. And the mode, whether light or dark, is stored on browser's local storage.
![image](https://github.com/zuramai/mazer/assets/76430369/10045012-1b51-40d6-a051-5b305a0294d0)

**Comment by alfianchii** [comment]
This issue already settled, I presumed. If there are other issues, you can create a new issue :)

**Comment by WhisperGo** [comment]
I'm afraid not, why when I open the mazer demo template, the default is dark?

**Comment by alfianchii** [comment]
@WhisperGo perhaps because your system settings

**Comment by WhisperGo** [comment]
> @WhisperGo perhaps because your system settings

Hmm, ok thanks i try change to light mode in my windows 10.😁

**Comment by alfianchii** [comment]
> > @WhisperGo perhaps because your system settings
> 
> Hmm, ok thanks i try change to light mode in my windows 10.😁

Nice!
