### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'getBoundingClientRect')

### ISSUE THREAD

**Issue by mogottsch** [zuramai/mazer#278]
I get this error message with the newest version when trying to render the sidebar without any active elements:
```
TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
```

I think the issue is in the `isElementInViewport` function.
If `el` is undefined this line fails:
```javascript
    var rect = el.getBoundingClientRect();
```

It seems like the issue exists since [this commit](https://github.com/zuramai/mazer/commit/60d7424078c94e646fa4dba34c3393d517e43300).

This fix works for me:
```javascript
    // Scroll into active sidebar
    setTimeout(() => {
      const activeSidebarItem = document.querySelector(".sidebar-item.active");
      if (activeSidebarItem) {
        this.forceElementVisibility(activeSidebarItem);
      }
    }, 300);
```

**Comment by mogottsch** [comment]
I can create a PR if the fix is fine for you.

**Comment by alfianchii** [comment]
> I can create a PR if the fix is fine for you.

Yup, please :)

**Comment by mogottsch** [comment]
I created a [PR here](https://github.com/zuramai/mazer/pull/279)  :)

**Comment by mocfaisal** [comment]
Whoaa, great 👍 
thanks for fixing it mate, I had the same problem
