### ISSUE TITLE
Vertical navbar Collapsable Menu not working

### ISSUE THREAD

**Issue by gokhansahin** [zuramai/mazer#285]
Vertical navbar Collapsable Menu not working. 
what could be the problem ?

**Comment by alfianchii** [comment]
> Vertical navbar Collapsable Menu not working. what could be the problem ?

Can you show to me what's wrong with the vertical navbar collapsable menu? For further details, you can sent screenshot or a video.

**Comment by gokhansahin** [comment]
![Ekran Alıntısı11](https://github.com/zuramai/mazer/assets/148655183/faab4fde-be9f-4c16-873a-fa71a6350538)

**Comment by reflymandau** [comment]
button function not working ?

**Comment by reflymandau** [comment]
First of all, delete your old assets folder, then extract the newest one until it's finished, then move it to your old assets folder, and try again!

**Comment by alfianchii** [comment]
As mentioned by @reflymandau, you can try the latest version of Mazer @gokhansahin. If your issue is not fixed, you can bring it back here.

**Comment by gokhansahin** [comment]
I downloaded the latest version and tried again and it works. Thank you
