### ISSUE TITLE
Error when using viettnamese language in latest version

### ISSUE THREAD

**Issue by dungdao191299** [zuramai/mazer#288]
Hi,  i using mazer template for my project. My UI using Vietnamese language . When i update to mazer latest version, it is bad to display vietnamese language. Can anyone fix that?
Sorry for my bad english.
This is my old display:
![image](https://github.com/zuramai/mazer/assets/54898195/801195be-936e-4bf9-9a3d-aef2eaf75456)

And this is my display after update:
![image](https://github.com/zuramai/mazer/assets/54898195/e7063b20-4435-4f00-9c4d-3b81147276f0)

**Comment by alfianchii** [comment]
Is your project using a custom font or automatic translation?

**Comment by alfianchii** [comment]
Can you provide to me what font is used in your project?

**Comment by dungdao191299** [comment]
> Can you provide to me what font is used in your project?

As far as i know that is Nunito font.
![image](https://github.com/zuramai/mazer/assets/54898195/1ac779f2-ba0e-4331-be7b-a4867f1773d0)
Is that default font in mazer template?

**Comment by alfianchii** [comment]
> am using default font (template in zip download release)

Yes, the default font of Mazer is Nunito. But wait, did you type the words in Vietnamese? Lemme know furthermore.

**Comment by dungdao191299** [comment]
> > am using default font (template in zip download release)
> 
> Yes, the default font of Mazer is Nunito. But wait, did you type the words in Vietnamese? Lemme know furthermore.

yes, i type vietnamese direcly to html.
i check in old version(2.0), it is have more nunito vietnamese font:
![image](https://github.com/zuramai/mazer/assets/54898195/6ba15880-f91f-466b-b7c8-217111da880e)

in latest version, have only latin nunito font:
![image](https://github.com/zuramai/mazer/assets/54898195/043f2add-4f7c-4573-9391-7465452f55fb)
is that problem i am face?

**Comment by alfianchii** [comment]
> yes, i type vietnamese direcly to html. 
> 
> i check in old version(2.0), it is have more nunito vietnamese font in latest version, have only latin nunito font
>
> is that problem i am face?


As you can see in old [_fonts.scss](https://github.com/zuramai/mazer/blob/5d71080102a0f88b289c26ea984adbd7f134adba/src/assets/scss/_fonts.scss), the fonts were included with `@import` directive, rather than being included directly as in the new of [_fonts.scss](https://github.com/zuramai/mazer/blob/main/src/assets/scss/_fonts.scss).

Therefore, if you want to keep it up the Vietnamese fonts, you can do the following steps:
- First of all, clone Mazer repository;
- Next, install its dependencies with `yarn install`;
- Once the deps installed, on `src/assets/scss/_fonts.scss`, change the codes just like on the old of [_fonts.scss](https://github.com/zuramai/mazer/blob/5d71080102a0f88b289c26ea984adbd7f134adba/src/assets/scss/_fonts.scss);
- After that, you can re-build the assets of Mazer with `npm run build` command;
- Finally, open up the builded assets on `dist/assets` folder. The `dist/assets` folder contains same as on the zip release file. You can therefore put it on your own project.
- And here we go, your Vietnamese font is going to work properly.

If the issue still persists, please let me know~~

## Screenshots
### _fonts.scss
![image](https://github.com/zuramai/mazer/assets/76430369/9c3d39bc-1905-4f0a-a743-804013e9e8e1)

### Before-after
![image](https://github.com/zuramai/mazer/assets/76430369/47439f39-9ebf-4a89-8492-8d10ff93de5c)
![image](https://github.com/zuramai/mazer/assets/76430369/ec61392f-a824-4e6f-8d2b-766f2f2c41b9)

**Comment by dungdao191299** [comment]
> > yes, i type vietnamese direcly to html.
> > i check in old version(2.0), it is have more nunito vietnamese font in latest version, have only latin nunito font
> > is that problem i am face?
> 
> As you can see in old [_fonts.scss](https://github.com/zuramai/mazer/blob/5d71080102a0f88b289c26ea984adbd7f134adba/src/assets/scss/_fonts.scss), the fonts were included with `@import` directive, rather than being included directly as in the new of [_fonts.scss](https://github.com/zuramai/mazer/blob/main/src/assets/scss/_fonts.scss).
> 
> Therefore, if you want to keep it up the Vietnamese fonts, you can do the following steps:
> 
> * First of all, clone Mazer repository;
> * Next, install its dependencies with `yarn install`;
> * Once the deps installed, on `src/assets/scss/_fonts.scss`, change the codes just like on the old of [_fonts.scss](https://github.com/zuramai/mazer/blob/5d71080102a0f88b289c26ea984adbd7f134adba/src/assets/scss/_fonts.scss);
> * After that, you can re-build the assets of Mazer with `npm run build` command;
> * Finally, open up the builded assets on `dist/assets` folder. The `dist/assets` folder contains same as on the zip release file. You can therefore put it on your own project.
> * And here we go, your Vietnamese font is going to work properly.
> 
> If the issue still persists, please let me know~~
> 
> ## Screenshots
> ### _fonts.scss
> ![image](https://private-user-images.githubusercontent.com/76430369/319802483-9c3d39bc-1905-4f0a-a743-804013e9e8e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjExMDEsIm5iZiI6MTcxMjgyMDgwMSwicGF0aCI6Ii83NjQzMDM2OS8zMTk4MDI0ODMtOWMzZDM5YmMtMTkwNS00ZjBhLWE3NDMtODA0MDEzZTllOGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA3MzMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNTM2YTgwMWQ3ODRkZjVmOGM4MmM4YmY4NjI2ZWJlNTcxMDgyMmZhNzlhYjFkOWEzNTk4Y2JiMmNjYThmMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eJseHzFAYrDzMU2q_PulZ5n9BfvYwW-Et2L0JGxLpXg)
> 
> ### Before-after
> ![image](https://private-user-images.githubusercontent.com/76430369/319802579-47439f39-9ebf-4a89-8492-8d10ff93de5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjExMDEsIm5iZiI6MTcxMjgyMDgwMSwicGF0aCI6Ii83NjQzMDM2OS8zMTk4MDI1NzktNDc0MzlmMzktOWViZi00YTg5LTg0OTItOGQxMGZmOTNkZTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA3MzMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YTAxZGI4YjQ5NTM3M2VhZjQ4MzMyOTI0MGIyZjRiNTRlNmExYjVjMmJhZWY2YWFjMTk0NmVkNjRhMWM3ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r7Dye2iCQkX1gTl8JXZ5DqDX_PMSfe7QluEMTX5FzEI) ![image](https://private-user-images.githubusercontent.com/76430369/319802575-ec61392f-a824-4e6f-8d2b-766f2f2c41b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjExMDEsIm5iZiI6MTcxMjgyMDgwMSwicGF0aCI6Ii83NjQzMDM2OS8zMTk4MDI1NzUtZWM2MTM5MmYtYTgyNC00ZTZmLThkMmItNzY2ZjJmMmM0MWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA3MzMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZmFiNjYwM2U4ODYwMzUyYjg0NjAwOTU5OWI4ZGJmMmUwZGI5ZjgzYTU1MWZkNmQ2NTdkNDlkMzQwYWQ4NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3gAJsbA5ocPzQgeKFHCmUvjvOOamqxyg7WOC5DSBfHA)

hi, thank your solution. To be honest, i am newbie in front-end program so i still learning. My level only use vanila js and html , css. I tried your instructions but it still doesn't complete. Can you send me your assets after re-build. I promise i will learn nodejs well after that

**Comment by dungdao191299** [comment]
> > yes, i type vietnamese direcly to html.
> > i check in old version(2.0), it is have more nunito vietnamese font in latest version, have only latin nunito font
> > is that problem i am face?
> 
> As you can see in old [_fonts.scss](https://github.com/zuramai/mazer/blob/5d71080102a0f88b289c26ea984adbd7f134adba/src/assets/scss/_fonts.scss), the fonts were included with `@import` directive, rather than being included directly as in the new of [_fonts.scss](https://github.com/zuramai/mazer/blob/main/src/assets/scss/_fonts.scss).
> 
> Therefore, if you want to keep it up the Vietnamese fonts, you can do the following steps:
> 
> * First of all, clone Mazer repository;
> * Next, install its dependencies with `yarn install`;
> * Once the deps installed, on `src/assets/scss/_fonts.scss`, change the codes just like on the old of [_fonts.scss](https://github.com/zuramai/mazer/blob/5d71080102a0f88b289c26ea984adbd7f134adba/src/assets/scss/_fonts.scss);
> * After that, you can re-build the assets of Mazer with `npm run build` command;
> * Finally, open up the builded assets on `dist/assets` folder. The `dist/assets` folder contains same as on the zip release file. You can therefore put it on your own project.
> * And here we go, your Vietnamese font is going to work properly.
> 
> If the issue still persists, please let me know~~
> 
> ## Screenshots
> ### _fonts.scss
> ![image](https://private-user-images.githubusercontent.com/76430369/319802483-9c3d39bc-1905-4f0a-a743-804013e9e8e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjM0MTMsIm5iZiI6MTcxMjgyMzExMywicGF0aCI6Ii83NjQzMDM2OS8zMTk4MDI0ODMtOWMzZDM5YmMtMTkwNS00ZjBhLWE3NDMtODA0MDEzZTllOGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzODQ5OTJhYWMyNTAyZDU3MWRiNjk2ODEzMGI3ZGQ4OTMyZjZkNmY4MTMxYjAwMzM1OTMzZjUxMDcxNGUzZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1jw2_71VeeCLPPLb6-LC7D69zbYn9I_nn1354ogYGck)
> 
> ### Before-after
> ![image](https://private-user-images.githubusercontent.com/76430369/319802579-47439f39-9ebf-4a89-8492-8d10ff93de5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjM0MTMsIm5iZiI6MTcxMjgyMzExMywicGF0aCI6Ii83NjQzMDM2OS8zMTk4MDI1NzktNDc0MzlmMzktOWViZi00YTg5LTg0OTItOGQxMGZmOTNkZTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMGU3MzM4MDdiYjc0ODY2Yjk5NDllMWY1ZDEzZDQxYmMzNzZiODY5NDk0OTIyMTk1YTM3YWJiZThjZGE2NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ON1u3KA13uerS93wWtxUthfsy_KezMOyi4_K0tB-4hs) ![image](https://private-user-images.githubusercontent.com/76430369/319802575-ec61392f-a824-4e6f-8d2b-766f2f2c41b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjM0MTMsIm5iZiI6MTcxMjgyMzExMywicGF0aCI6Ii83NjQzMDM2OS8zMTk4MDI1NzUtZWM2MTM5MmYtYTgyNC00ZTZmLThkMmItNzY2ZjJmMmM0MWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYmZhY2YwYWYyOTBjNGE1NjMxMDQ1ZmZiYjE3MjdhZGVhOGU4Mjg2ODZjMWI1MDBlNWZkOGQzOTA2YTMwMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ToYjrx39ANNgLMMQOQCeQXjOUkNuvfUj4QvCxWiJMM)

it working, thank you so much

**Comment by fdobrovolny** [comment]
After updating Mazer to the latest version, I also ran into this issue with European languages (latin-extended).

So, I made a fork and backported this fix to all affected versions. As we are using this in production, we will also provide updates.

https://github.com/fdobrovolny/mazer

In releases, you can download the prebuilt templates.zip file for affected versions.
