### ISSUE TITLE
How to create a dynamic menu

### ISSUE THREAD

**Issue by Macfee** [zuramai/mazer#295]
Hello everyone, I would like to ask for some advice. This UI is great and is perfect for my front-end and back-end project. Now, I want to create a dynamic menu. Could you please advise me on how to set it up?

**Comment by RomanBobkov** [comment]
@Macfee hello!
All what you need is manage 
`<li class="sidebar-item">
        <a href="/" class="sidebar-link">
            <i class="bi bi-grid-fill"></i>
            <span>Menu item name</span>
        </a>
    </li>`
items.
I see you use Django.
Then you can render template using conditions.
Like
`{% if showSettings %}
<li class="sidebar-item">
      <a href="/settings" class="sidebar-link">
          <i class="bi bi-grid-fill"></i>
          <span>Settings</span>
      </a>
  </li>
{% endif %}
`
Hope it helps.

**Comment by alfianchii** [comment]
Thanks to @RomanBobkov. Hope it helps! @Macfee
