### ISSUE TITLE
Sidebar Hide in Default

### ISSUE THREAD

**Issue by fitrinurazizah** [zuramai/mazer#296]
Can I make the sidebar hide by default when using the Vertical Navbar layout?
How to make it?

**Comment by mocfaisal** [comment]
you can use this javascript
```javascript
var element = document.getElementById("sidebar");
element.classList.remove("active")
element.classList.add("inactive")
```

**Comment by fitrinurazizah** [comment]
sidebar doesn't auto hide and only the main content is full screen but covered by the sidebar with that script

**Comment by fitrinurazizah** [comment]
I found it, I changed the app.js part (U.classList.add("active"),U.classList.add("sidebar-desktop"));
I changed it from active to inactive
