### ISSUE TITLE
Add a comment button for anyone to add a new comment.

### ISSUE THREAD

**Issue by mrunal1309** [zuramai/mazer#300]
There is no option of adding a new comment for new or existing users.
@zuramai can you please assign me this issue?
![Screenshot 2024-10-02 093157](https://github.com/user-attachments/assets/8fd4fdf3-7e11-4942-b32b-5fc5521b9e6c)

**Comment by zuramai** [comment]
I appreciate your willingness to add a feature, but the purpose of this card is just to show latest comments, not to add comment.
