### ISSUE TITLE
Some of the texts on the dashboard are out of elements.

### ISSUE THREAD

**Issue by Zzzul** [zuramai/mazer#38]
## Screenshots
<img width="960" alt="mazer issue" src="https://user-images.githubusercontent.com/62506582/135562531-86e6d1bd-8d2c-4150-a9e2-e9166a38acc5.png">

![135372347-cfaeb537-fa70-499d-ac6d-0f957a1fef8f](https://user-images.githubusercontent.com/62506582/135561731-6985775c-92ff-4996-8b78-8103293807ee.png)
![135372387-179d4260-540d-4b1f-9f3d-7af413c95e67](https://user-images.githubusercontent.com/62506582/135561738-62072295-8bf2-47b7-8539-e81ca62b9da2.png)
![135372428-75e523e4-084f-4e69-b00a-9ef6b99ce995](https://user-images.githubusercontent.com/62506582/135561742-83aef31b-f091-4ea7-a647-c8df11157cd0.png)

### Browser
- Edge - Version  92.0.902.78 (Official build) (64-bit), with default zoom(100%)

### Screen size
- 13.3"

### Display Settings
![135372639-6609ce39-20f9-45f4-9eb3-cd6179c57b2f](https://user-images.githubusercontent.com/62506582/135562229-4a12e05d-2e2c-45cf-abb6-c8658c9a3b28.png)

**Comment by Salisyal** [comment]
hello, I have fixed the problem in the template, you can check my pull request to see it

**Comment by akshat-kumar2109** [comment]
Can you assign me this issue @Zzzul

**Comment by RioChndr** [comment]
I recommend to implement global css like this to prevent overflow text
```css
div {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

**Comment by bl0cknumber** [comment]
> I recommend implementing global CSS like this to prevent overflow text
> 
> ```css
> div {
>   white-space: nowrap;
>   overflow: hidden;
>   text-overflow: ellipsis;
> }
> ```

I would prefer to use a simple approach, it has fairly has good browser supports, read https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap.

```CSS
overflow-wrap: break-word;
```

Except for IE9, it does not recognize overflow-wrap but works fine with word-wrap, so adding both would suffice since it's much simple than using conditional rules.

```CSS
word-wrap: break-word;
overflow-wrap: break-word;
```
