### ISSUE TITLE
Halaman Login dan Registrasi tidak bisa discroll di HP

### ISSUE THREAD

**Issue by joshpob** [zuramai/mazer#4]
Hai kak, saya ingin menggunakan Mazer Bootstrap ini untuk project saya. Saat saya mencoba mengakses halaman login di desktop komputer, semuanya aman-aman saja. Tetapi kalau diakses menggunakan HP maka akan mentok di atas tombol login seperti gambar ini:
https://res.cloudinary.com/dyvkwgumz/image/upload/v1611399517/IMG_20210123_175644_kqfnei.jpg

Kode belum saya ubah sama sekali. Apakah ada solusi? Terima kasih sebelumnya :D

**Comment by fauzan121002** [comment]
Silahkan coba di pull ulang kak :D

Ref : https://github.com/zuramai/mazer/pull/5
