### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by ali-sheykhi** [zuramai/mazer#46]
The **Choices**  documentation link was broken in **this page:** 

https://zuramai.github.io/mazer/demo/form-element-select.html

**and brokend link is :**
https://choices.org/getting-started/installation

 and i cant **finde** the libery website or Github link

**Comment by zuramai** [comment]
The actual github pages from the library is also broken, I don't know if they're actually still maintaining it. But I think you can take a look at this

https://github.com/Choices-js/Choices/tree/gh-pages
