### ISSUE TITLE
Horizontal Layout - Merge the menu bar and logo bar

### ISSUE THREAD

**Issue by ak-2020** [zuramai/mazer#53]
The logo bar occupies a lot of space and shows nothing but logo.  Is it possible to merge the 2 bars together to have a single bar?

**Comment by dragstor** [comment]
> The logo bar occupies a lot of space and shows nothing but logo. Is it possible to merge the 2 bars together to have a single bar?

Other than the logo, it holds the place for a hamburger menu 😃 

![Screenshot from 2021-12-10 22-51-59](https://user-images.githubusercontent.com/363811/145646060-2d289c21-084e-4f8c-b63b-6045e237be29.png)

**Comment by zuramai** [comment]
It is possible. 
Actually, the topbar is also made for user dropdown like this:

![image](https://user-images.githubusercontent.com/45036724/146277471-d7372724-cba1-44b9-8169-28056e2b2f5f.png)

Check out 5847ee8
