### ISSUE TITLE
Tampilan beda dibootstrap ^5.1.3

### ISSUE THREAD

**Issue by lumine-id** [zuramai/mazer#54]
Saya pake bootstrap versi 5.1.3 kok beda ya tampilannya dari dropdown dll, ga seperti didemo. saya cek didemo pake bootstrap v5.0.0-alpha2 lalu saya coba install bootstrap v5.0.0-alpha2 lewat npm tapi pas jalanin mix error undefined variable blablabal.

**Comment by zuramai** [comment]
Boleh minta screenshot errornya?

**Comment by lumine-id** [comment]
![IMG_20211226_135814](https://user-images.githubusercontent.com/87742775/147401311-511fbcd6-43dd-4800-8120-0c7e856a4ed7.jpg)

bootstrap 5.0.0alpha2

**Comment by zuramai** [comment]
Fixed. c586b53
