### ISSUE TITLE
datatable

### ISSUE THREAD

**Issue by miguelribeirooo** [zuramai/mazer#56]
good night, I would like to know how this part of the code is working, how do you call the dataTable variable?
![Captura de tela 2022-02-09 135355](https://user-images.githubusercontent.com/57357424/153249864-e6cf9947-814a-45bb-a44d-f3c60640d7d1.jpg)

**Comment by Nugjii** [comment]
Hi, I think dataTable variable not called anywhere. It is for just create new DataTabe instatnce.

**Comment by zuramai** [comment]
once `new simpleDatatables.DataTable(table1)` called, then the table will automatically using DataTable
