### ISSUE TITLE
bootstrap accordion is not working properly

### ISSUE THREAD

**Issue by herupurwito** [zuramai/mazer#57]
looks like the _accordion.scss file is not in assets

![image](https://user-images.githubusercontent.com/1225174/154455038-3e218fe0-dbfe-4f82-8853-a84de6319930.png)
this is the view from the bootstrap documentation
![image](https://user-images.githubusercontent.com/1225174/154455174-9c7cfb6a-e246-4540-aebd-9affcf441333.png)
 
please fix this, it's better to use a package manager like NPM/Yarn

**Comment by zuramai** [comment]
Fixed by upgrading the bootstrap to v5.1.3. 
Check out 30e91cf

**Comment by herupurwito** [comment]
thanks, finally upgraded the bootstrap to v5.1.3
