### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by mesayuda** [zuramai/mazer#61]
Hi everyone,

Please, you can tell me if exist a darkmode in this template and how activate it? thanks

**Comment by zuramai** [comment]
Currently, there's no dark theme in this template. But we'll look forward into that feature, thank you!

**Comment by kazemyavari** [comment]
> Currently, there's no dark theme in this template. But we'll look forward into that feature, thank you!

Hi everyone,

Thanks to ahmad saugi, I have added a dark mode to this template. Please visit and let me know if there is a problem so I can fix it. Also, if possible, if you put a dark mode link on the page of this template, it will make me happy.

**Comment by zuramai** [comment]
Great!
Thank you @kazemyavari for the dark mode, I have added the link to your repository in the README.
