### ISSUE TITLE
DateTimePicker or DatePicker

### ISSUE THREAD

**Issue by chrlsbyrndlcrz** [zuramai/mazer#63]
Hi

I love Mazer Template, is there possible to add the DateTime Picker component

Thanks

**Comment by zuramai** [comment]
It is possible, we will add the Date/DateTime Picker component. Any ideas what's the best library that we could use?

**Comment by chrlsbyrndlcrz** [comment]
the already add to my local template, i use this  https://bootstrap-datepicker.readthedocs.io/en/latest/

**Comment by hhelderneves** [comment]
I personally use type="date" , works fine and doesn't need any package.

**Comment by gvnnunes** [comment]
Any prevision for this feature ?

**Comment by gvnnunes** [comment]
Any predictions for this feature?

**Comment by gregorydk** [comment]
The input type "date" might be sufficient in some cases but it's limited and cannot be styled.

The other 2 I suggested are probably not maintained any more, flatpickr might be a better choice.

https://flatpickr.js.org/
