### ISSUE TITLE
Is it possible to remove the copyright notice from the footer

### ISSUE THREAD

**Issue by Aloha276** [zuramai/mazer#74]
Is it possible to remove the copyright notice from the footer and use the theme for commercial purpose?

**Comment by zuramai** [comment]
Yes you can.
You only need to keep the copyright when you want to redistribute the code.

**Comment by Aloha276** [comment]
Thanks a lot!

I want to use the Mazer theme in a Laravel based app, so if i add the Mazer's LICENSE file to the root of the project it would be as if the entire project is under MIT license.

Where should I include the Mazer's MIT license notice in this case?

I'm new to the software licensing world so please bear with me :)

**Comment by zuramai** [comment]
If you want to make an app that is using Mazer, you can change the LICENSE as your wish according to your project. You are only required to provide the license when you want to redistribute the source code.

**Comment by Aloha276** [comment]
Ah okay i see, Thanks a lot for the clarification!
