### ISSUE TITLE
Error in error-403.png

### ISSUE THREAD

**Issue by gregorydk** [zuramai/mazer#75]
Error image `error-403.png` has 404 written in it instead of 403.

**Comment by Niksac** [comment]
This has been fixed in [this commit](https://github.com/zuramai/mazer/commit/ec04b2409f00b0d366ee7ef2cca65a951d8ab885).
You can use the new image from there or use the [2.0.0-rc.1](https://github.com/zuramai/mazer/tree/2.0.0-rc.1).
