### ISSUE TITLE
Top bar

### ISSUE THREAD

**Issue by ParalaX002** [zuramai/mazer#79]
Hi,

For a project I would need a top bar in addition to the menu. This top bar should stay on all the time, a bit like on the bootstrap website (the search bar)
https://getbootstrap.com/docs/5.0/getting-started/introduction/?msclkid=abc7beefcd1811eca88527d4f74665f3

I've managed to do something, but it overlaps with the menu. Is this something you would consider to add in the next release?

Regards,

**Comment by zuramai** [comment]
Hi @ParalaX002,
You can achieve the same way like Bootstrap's documentation navbar with `position: sticky`.

![image](https://user-images.githubusercontent.com/45036724/167124204-d6cd6dbc-400f-4daf-8857-e3d1f23c5178.png)

As you can see in the image above, try adding `position: sticky`, `top: 0`, `z-index: 5` to the navbar. And if it doesn't work, try to add `display: initial` to the parent element.

**Comment by zuramai** [comment]
Do you have any screenshot how it would look like?

**Comment by ParalaX002** [comment]
Here it is if I set the bar bellow the sidebar:
![image](https://user-images.githubusercontent.com/24775366/167136181-aaf20d90-7378-430f-b155-75f6746bc119.png)

Or, if I put it on top:
![image](https://user-images.githubusercontent.com/24775366/167136741-83866e53-ad5c-4188-b843-8f6dad9ddc7d.png)
To put it on top, I add the class "sticky-top" to the "bd-subnavbar", like this:
  `<nav class="bd-subnavbar  sticky-top">`

As you can see, either the logo is dropped, or the begining of the sidebar. I can play with some margin and padding, but then it doesn't looks nice when I resize the window...

**Comment by zuramai** [comment]
You can try to set a background to the navbar, and set a full width.

Another option:
If you need navbar in Mazer, you can take [layout-vertical-navbar.html](https://github.com/zuramai/mazer/blob/657e7b34881f74ff3808400baafcaca323805902/dist/layout-vertical-navbar.html#L414-L416) as reference.

The structure is to make navbar is like this:
```html
<div id="app">
    <div id="sidebar" class="active">
        <div class="sidebar-wrapper active">
                 // Sidebar items
        </div>
    </div>
    <div id="main" class='layout-navbar'>
        <header class='mb-3'>
            <nav class="navbar navbar-expand navbar-light ">
                   // Your bootstrap navbar here
            </nav>
        </header>

        // app content..
</div>
```

**Comment by ParalaX002** [comment]
Hi, thanks for your help :)

I managed to get something, it's still not perfect because it is not resizing correctly to the content yet, but it'll do. Maybe it would be a good addition to create an example with both bars in your demo :)

Regards
