### ISSUE TITLE
Bootstrap collapsible don't hide

### ISSUE THREAD

**Issue by ParalaX002** [zuramai/mazer#84]
Hi,

I think there might be an interference with bootstrap collapsible (for instance like this: https://getbootstrap.com/docs/5.0/components/collapse/)

When app.js is called, the collapsibles don't hide anymore.

Thanks :)

**Comment by zuramai** [comment]
Is there any error in the console when you are trying to open/close the collapse?

**Comment by ParalaX002** [comment]
Unfortunately not :(

**Comment by zuramai** [comment]
It's work as of [v2.0.0-rc.1](https://github.com/zuramai/mazer/releases/tag/v2.0.0-rc.1).
And I've added the Collapse page, you can check in the demo for [collapse page](https://zuramai.github.io/mazer/demo/component-collapse.html).

**Comment by ParalaX002** [comment]
Great, thanks a lot :)
