### ISSUE TITLE
Bug form-modal on dark-mode

### ISSUE THREAD

**Issue by zeinalaydrus** [zuramai/mazer#87]
![Screenshot from 2022-05-31 16-02-57](https://user-images.githubusercontent.com/97078417/171147652-92b6101c-1149-47c6-a75a-86da7275957e.png)

when the form fill by recommendation text fill,  it will turn into light mode.
but when we type manual it will still be dark theme

**Comment by bagussatoto** [comment]
# @zeinalaydrus 

# Please be patient, we will fix it soon, thank you for commenting on issues
