### ISSUE TITLE
Upgrade to bootstrap 5.2.0

### ISSUE THREAD

**Issue by zuramai** [zuramai/mazer#88]
Mazer v2.0 will be released after these features implemented:
- Upgrade to Bootstrap v5.2.0
- Adding pages for components (popovers, offcanvas, toasts, etc)

**Comment by Harixomxsingh** [comment]
hey 🙋‍♂️ can you add me

**Comment by bagussatoto** [comment]
> # @zuramai  

# I also want to contribute to this project

**Comment by zuramai** [comment]
Hi @bagussatoto @Harixomxsingh, you can read the [CONTRIBUTING.md](https://github.com/zuramai/mazer/blob/main/CONTRIBUTING.md) and create a pull request.

**Comment by Harixomxsingh** [comment]
ok I am working on it, when my work is done then I create a PR

**Comment by zuramai** [comment]
Closed as ed73f6de771e464d5d74e4c8ece213e419830bfe
