### ISSUE TITLE
Horizontal Layout - Dropdown in topbar not working

### ISSUE THREAD

**Issue by superdisc** [zuramai/mazer#92]
I don't see this dropdown when hovering the mouse on image. Could you help?

![image](https://user-images.githubusercontent.com/49386329/172158712-9bb71952-dc54-49b9-89b6-f1f75d8eb0d3.png)

**Comment by zuramai** [comment]
At `layout-horizontal.html`, you can find this piece of code that you can use to make that dropdown.

![image](https://user-images.githubusercontent.com/45036724/172347244-6021ef08-13e7-45e6-873d-1f2a01ee18a9.png)

**Comment by xLinkOut** [comment]
I also noticed that the dropdown on the profile picture in the horizontal layout does not work. It doesn't work in the demo on [this page](https://zuramai.github.io/mazer/demo/layout-horizontal.html) either.

**Comment by superdisc** [comment]
Thanks for fixing it
