### ISSUE TITLE
need help datatable (jQuery) (Button Export)

### ISSUE THREAD

**Issue by nabielmada** [zuramai/mazer#99]
HI! need help
How add button html5 export (csv,excel,pdf) and print in your datatable (jQuery) ?

I Love this Mazer Template,
Thank You

**Comment by zuramai** [comment]
Hi, you can check the documentation of the jQuery DataTables here
https://datatables.net/

**Comment by nabielmada** [comment]
i've tried it's working but the display changes to a Datatables style, how can I just add the export button but the display remains like the Mazer style?

I tried again in the dist/assets/js/extensions/datatables.js file, with the Datatables JS and CSS library :
CSS: 
https://cdn.datatables.net/buttons/2.2.3/css/buttons.dataTables.min.css
JS:
https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js
https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js
https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js
https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js
https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js

dist/assets/js/extensions/datatables.js file:
`var jquery_datatable = $("#table1").DataTable({
	dom: 'Bfrtip',
	buttons: [
		'copyHtml5',
		'excelHtml5',
		'csvHtml5',
		'pdfHtml5'
	]
});`

it's not working

Thank you for your reply
